[project]
name = "ml-foundations"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Artem Miroshnichenko", email = "neoforeve@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "numpy>=2.5.3",
    "torch>=2.14.0",
]

[project.scripts]
ml-foundations = "ml_foundations:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "mypy>=2.3.1",
    "ruff>=0.16.8",
]

[tool.mypy]
strict = true

[tool.ruff]
# Игнорируем требование обязательного копирайта во всех файлах
lint.ignore = ["CPY001","D203","D213", "COM812"]
